// src/components/EditTicketForm.vue
<!-- src/components/EditTicketForm.vue -->
<script setup lang="ts">
import { ref, watch } from 'vue';
import { updateTicket, type Ticket, type TicketStatus } from '../lib/tickets';
// Use the global toast function (assuming vue-toastification setup)
import { useToast } from 'vue-toastification';
// Import the Vue-compatible icon component
import {AlertCircle} from 'lucide-vue-next';

// --- PROPS & EVENTS ---

// Define the required props
const props = defineProps<{
  ticket: Ticket;
}>();

// Define the custom event (replaces onSuccess)
const emit = defineEmits<{
  (e: 'success'): void;
}>();

// --- SETUP ---
const toast = useToast();

// --- STATE (ref replaces useState) ---
// Initialize form fields with prop values
const title = ref(props.ticket.title);
const description = ref(props.ticket.description);
const status = ref<TicketStatus>(props.ticket.status);
const priority = ref(props.ticket.priority);
const error = ref("");
const isLoading = ref(false);

// WATCHER: Reset form state if the parent component passes a new ticket prop
// This ensures the form updates if the user selects a different ticket in the parent list.
watch(() => props.ticket, (newTicket) => {
  title.value = newTicket.title;
  description.value = newTicket.description;
  status.value = newTicket.status;
  priority.value = newTicket.priority;
  error.value = "";
  isLoading.value = false;
}, { deep: true });


// --- METHODS ---
const handleSubmit = () => {
  error.value = "";
  isLoading.value = true;

  if (!title.value.trim()) {
    error.value = "Title is required";
    isLoading.value = false;
    return;
  }

  if (!description.value.trim()) {
    error.value = "Description is required";
    isLoading.value = false;
    return;
  }

  try {
    // Call the utility function to update the ticket
    updateTicket(props.ticket.id, { 
      title: title.value, 
      description: description.value, 
      status: status.value, 
      priority: priority.value 
    });
    
    toast.success("Ticket updated successfully!");
    // Emit the success event (replaces onSuccess)
    emit('success'); 

  } catch (err) {
    console.error("Update error:", err);
    error.value = "Failed to update ticket";
  }

  isLoading.value = false;
};
</script>

<template>
  <!-- @submit.prevent handles form submission in Vue -->
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <!-- Error Alert -->
    <div v-if="error" class="flex gap-3 rounded-lg bg-destructive/10 p-3 border border-destructive/20">
      <AlertCircle class="h-5 w-5 text-destructive shrink-0 mt-0.5" />
      <p class="text-sm text-destructive">{{ error }}</p>
    </div>

    <!-- Title Input -->
    <div>
      <label
        for="title"
        class="block text-sm font-medium text-foreground mb-2"
      >
        Title
      </label>
      <input
        id="title"
        type="text"
        v-model="title"
        class="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
        :disabled="isLoading"
      />
    </div>

    <!-- Description Textarea -->
    <div>
      <label
        for="description"
        class="block text-sm font-medium text-foreground mb-2"
      >
        Description
      </label>
      <textarea
        id="description"
        v-model="description"
        rows="4"
        class="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none"
        :disabled="isLoading"
      />
    </div>

    <!-- Status and Priority Selects -->
    <div class="grid grid-cols-2 gap-4">
      <!-- Status Select -->
      <div>
        <label
          for="status"
          class="block text-sm font-medium text-foreground mb-2"
        >
          Status
        </label>
        <select
          id="status"
          v-model="status"
          class="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
          :disabled="isLoading"
        >
          <option value="open">Open</option>
          <option value="in-progress">In Progress</option>
          <option value="closed">Closed</option>
        </select>
      </div>

      <!-- Priority Select -->
      <div>
        <label
          for="priority"
          class="block text-sm font-medium text-foreground mb-2"
        >
          Priority
        </label>
        <select
          id="priority"
          v-model="priority"
          class="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
          :disabled="isLoading"
        >
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
      </div>
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      :disabled="isLoading"
      class="w-full rounded-lg bg-primary px-4 py-2 font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
    >
      {{ isLoading ? "Updating..." : "Update Ticket" }}
    </button>
  </form>
</template>

// src/components/edit-ticket-form.tsx
"use client";

import type React from "react";

import { useState } from "react";
import { updateTicket, type Ticket, type TicketStatus } from "@/lib/tickets";
import { AlertCircle } from "lucide-react";
import { toast } from "react-toastify";

interface EditTicketFormProps {
  ticket: Ticket;
  onSuccess: () => void;
}

export function EditTicketForm({ ticket, onSuccess }: EditTicketFormProps) {
  const [title, setTitle] = useState(ticket.title);
  const [description, setDescription] = useState(ticket.description);
  const [status, setStatus] = useState<TicketStatus>(ticket.status);
  const [priority, setPriority] = useState(ticket.priority);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);

    if (!title.trim()) {
      setError("Title is required");
      setIsLoading(false);
      return;
    }

    if (!description.trim()) {
      setError("Description is required");
      setIsLoading(false);
      return;
    }

    try {
      updateTicket(ticket.id, { title, description, status, priority });
      toast.success("Ticket updated successfully!");
      onSuccess();
    } catch (err) {
      setError("Failed to update ticket");
    }

    setIsLoading(false);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {error && (
        <div className="flex gap-3 rounded-lg bg-destructive/10 p-3 border border-destructive/20">
          <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
          <p className="text-sm text-destructive">{error}</p>
        </div>
      )}

      <div>
        <label
          htmlFor="title"
          className="block text-sm font-medium text-foreground mb-2"
        >
          Title
        </label>
        <input
          id="title"
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
          disabled={isLoading}
        />
      </div>

      <div>
        <label
          htmlFor="description"
          className="block text-sm font-medium text-foreground mb-2"
        >
          Description
        </label>
        <textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={4}
          className="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none"
          disabled={isLoading}
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label
            htmlFor="status"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Status
          </label>
          <select
            id="status"
            value={status}
            onChange={(e) => setStatus(e.target.value as TicketStatus)}
            className="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
            disabled={isLoading}
          >
            <option value="open">Open</option>
            <option value="in-progress">In Progress</option>
            <option value="closed">Closed</option>
          </select>
        </div>

        <div>
          <label
            htmlFor="priority"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Priority
          </label>
          <select
            id="priority"
            value={priority}
            onChange={(e) =>
              setPriority(e.target.value as "low" | "medium" | "high")
            }
            className="w-full rounded-lg border border-input bg-background px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
            disabled={isLoading}
          >
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>
        </div>
      </div>

      <button
        type="submit"
        disabled={isLoading}
        className="w-full rounded-lg bg-primary px-4 py-2 font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {isLoading ? "Updating..." : "Update Ticket"}
      </button>
    </form>
  );
}
